name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and test
        run: ./gradlew :plugin:build :plugin:test